name: Deployment
on: 
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Update Server
        uses: appleboy/ssh-action@master
        with:
          host: athesto.ddns.net
          username: alexander_i_bakalov
          key: ${{ secrets.PRIVKEY_SECRET }}
          port: 22
          script: |
            cd ~/AAC/ 
            git pull origin master
            git status

