name: Deployment
on: 
  push:
    branches: [ dev ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Update Server
        uses: appleboy/ssh-action@master
        with:
          host: athesto-dev.ddns.net
          username: pi
          key: ${{ secrets.DEV_PRIVKEY_SECRET }}
          port: 2222
          script: |
            cd ~/github/Algorithums-and-Astronomy-Calculator/ 
            git pull origin dev
            git status

