name: Go

on:
  push:
    branches: 
      - master
      - dev
  pull_request:
    branches: 
      - master
      - dev

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Go Mod Setup
      run: go mod init example.com/m/v2
      
    - name: Build
      run: go build -v ./Go/server.go

    - name: Test
      run: go test -v ./Go/server.go
